config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :questions, only: [:index, :show]
  resources :users do
    collection do
      post :follow_topic
      post :follow_user
    end
  end

  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :ans_content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :answers
  validates :content, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :user_topics
  has_many :users, through: :user_topics

  enum category: {"science" => 0, "defence" => 1, "politics" => 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :user_topics
  has_many :topics, through: :user_topics
  # has_many :following_relationships, foreign_key: "follower_id", class_name: "Follower"
  # has_many :user_relationships, foreign_key: "following_id", class_name: "Following"
  # has_many :following_users, through: :following_relationships, source: :following_users
  has_many :user_relationships

  def following
    user_relationships.where(relation_type: "following", relationable_id: id)
  end

  def follower
    user_relationships.where(relation_type: "follower", relationable_id: id)
  end
end

app/models/user_relationship.rb
class UserRelationship < ApplicationRecord
  # belongs_to :follower_user, class_name: 'User', foreign_key: "follower_id"
  # belongs_to :following_user, class_name: 'User', foreign_key: "following_id"
  belongs_to :user
  validates :relation_type, inclusion: { in: %w(follower following),
    message: "%{value} is not a valid type" }
end

app/models/user_topic.rb
class UserTopic < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  validates_uniqueness_of :user_id, scope: :topic_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.includes(:topic).find_by(id: params[:id])
    @answers = @question.answers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def follow_topic
    ut = current_user.user_topics.new(topic_id: params[:topic_id])
    if ut.save
      redirect_to questions_path
    else
      redirect_to questions_path
      flash[:alert] = "You already followed this topic"
    end
  end

  def follow_user
    user = Question.find_by(id: params[:question_id]).user
    ur = user.user_relationships.new(relationable_id: current_user.id, relation_type: "following")
    if ur.save
      redirect_to questions_path
      flash[:notice] = "You start follow this user"
    else
      redirect_to questions_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OkodersAss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<%if user_signed_in? %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary'%>
<% end %>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<% unless @questions.nil? %>
  <% if @questions.empty? %>
    <h3>No Question found.</h3>
  <% else %>
    <h3>Search results</h3>

    <table>
      <thead>
         <tr>
          <th>Question</th>
          <th>Action</th>
         </tr>
      </thead>

      <tbody>
        <% @questions.each do |que| %>
          <tr>
            <td><%= que.content %></td>
            <td><%= link_to "Show", question_path(que)%></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>

app/views/questions/show.html.erb
<% @answers.each do |ans|%>
  <li class="answer"><%= ans.ans_content%></li>
<% end %>

<%= link_to "Follow User", follow_user_users_path(question_id: @question.id), method: :post, class: 'follow_user'%>
<%= link_to "Follow Topic", follow_topic_users_path(topic_id: @question.topic.id), method: :post, class: 'follow_topic'%>